# Generated by Django 4.0.6 on 2022-09-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_post_vote_ratio_post_vote_total_review_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='título',
            new_name='title',
        ),
    ]
